// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCazf9iif_03-tb7pPNA3uPlc73GZhQviM',
    appId: '1:574222921691:web:31c29b0da58e9a9ed901fe',
    messagingSenderId: '574222921691',
    projectId: 'cmsc23-final-project-b96e9',
    authDomain: 'cmsc23-final-project-b96e9.firebaseapp.com',
    storageBucket: 'cmsc23-final-project-b96e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp9pvvFYySA4V_dZa1DUgy54TrZIrHFGM',
    appId: '1:574222921691:android:c4319cd23b0cf732d901fe',
    messagingSenderId: '574222921691',
    projectId: 'cmsc23-final-project-b96e9',
    storageBucket: 'cmsc23-final-project-b96e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Ha1_XGcfu9UU2i1GLanq40sv1bS4IGw',
    appId: '1:574222921691:ios:2a7f9948d3d385efd901fe',
    messagingSenderId: '574222921691',
    projectId: 'cmsc23-final-project-b96e9',
    storageBucket: 'cmsc23-final-project-b96e9.appspot.com',
    iosClientId: '574222921691-q79v6sf8bg6r6lpe74rpfgpnq6toa5fe.apps.googleusercontent.com',
    iosBundleId: 'com.example.bounceFinalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Ha1_XGcfu9UU2i1GLanq40sv1bS4IGw',
    appId: '1:574222921691:ios:9994eee94102ae4dd901fe',
    messagingSenderId: '574222921691',
    projectId: 'cmsc23-final-project-b96e9',
    storageBucket: 'cmsc23-final-project-b96e9.appspot.com',
    iosClientId: '574222921691-5jartrib5shekmfdit5ufiomjq9oip3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.bounceFinalproject.RunnerTests',
  );
}
